sage random_script.sage -n 3 -md 2 -reps 10 -g -u
sage random_script.sage -n 4 -md 2 -reps 10 -g -u
sage random_script.sage -n 5 -md 2 -reps 10 -g -u
sage random_script.sage -n 6 -md 2 -reps 10 -g -u
sage random_script.sage -n 7 -md 2 -reps 10 -g -u
sage random_script.sage -n 8 -md 3 -reps 10 -g -u
sage random_script.sage -n 9 -md 3 -reps 10 -g -u
sage random_script.sage -n 10 -md 3 -reps 10 -g -u
sage random_script.sage -n 11 -md 3 -reps 10 -g -u
sage random_script.sage -n 12 -md 3 -reps 10 -g -u
sage random_script.sage -n 13 -md 3 -reps 10 -g -u
sage random_script.sage -n 14 -md 3 -reps 10 -g -u
sage random_script.sage -n 15 -md 3 -reps 10 -g -u
sage random_script.sage -n 16 -md 3 -reps 10 -g -u